Disable calendar for vx7r2cert
AdaCore/aunit pull request #30
Opened 2021-03-16 16:48 UTC by jklmnn

TN: U216-007

2021-03-16 16:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AdaCore/aunit?pullRequest=30) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AdaCore/aunit?pullRequest=30) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AdaCore/aunit?pullRequest=30) it.</sub>

2021-03-17 06:08 UTC, brobecke requested changes
Hi Johannes,

I'd like to suggest we change the subject to be more precise, since we're not disabling calendar for a given platform, but actually a given runtime. How about...

Disable calendar when using "cert" runtime

?

2021-03-17 11:18 UTC, jklmnn commented
Would `Disable calendar for vx7r2cert runtime` be sufficient? Since we're e.g. not disabling it for the lynxos cert runtime. At least no in this PR?

2021-03-17 11:20 UTC, jklmnn commented
Fixed in https://github.com/AdaCore/aunit/pull/30/commits/bdb736162afd58536e60f70051589841563e031a.

2021-03-17 11:37 UTC, brobecke approved these changes

2021-03-17 11:40 UTC, merged